server:
  port: '8081'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/books
    password: '12345'
  thymeleaf:
    prefix: classpath:/templates/
    cache: 'false'
    suffix: .html
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  security:
    oauth2:
      client:
        registration:
         google:
           client-id: 943084645446-q94ua60ft56pblmn5b98dd8nush0h908.apps.googleusercontent.com
           client-secret: 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
           scope: profile, email